### ISSUE TITLE
No middlewares works

### ISSUE THREAD

**Issue by BoGnY** [bnf/slim3-psr15#1]
Hi, I'm trying your implementation of psr-15 with slim3, but I give this error:

> Slim Application Error
> The application could not run because of the following error:
> 
> Details
> Type: RuntimeException
> Message: {} is not resolvable
> File: C:\wamp\www\yav-website\vendor\slim\slim\Slim\CallableResolver.php
> Line: 104
> Trace
> #0 C:\wamp\www\yav-website\vendor\slim\slim\Slim\CallableResolver.php(56): Slim\CallableResolver->assertCallable(Object(Middlewares\HtmlMinifier))
> #1 C:\wamp\www\yav-website\vendor\slim\slim\Slim\CallableResolverAwareTrait.php(45): Slim\CallableResolver->resolve(Object(Middlewares\HtmlMinifier))
> #2 C:\wamp\www\yav-website\vendor\slim\slim\Slim\DeferredCallable.php(36): Slim\DeferredCallable->resolveCallable(Object(Middlewares\HtmlMinifier))
> #3 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
> #4 C:\wamp\www\yav-website\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
> #5 C:\wamp\www\yav-website\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
> #6 C:\wamp\www\yav-website\vendor\slim\slim\Slim\App.php(388): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
> #7 C:\wamp\www\yav-website\vendor\slim\slim\Slim\App.php(296): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
> #8 C:\wamp\www\yav-website\public\index.php(26): Slim\App->run()
> #9 {main}

This error means that your CallableResolver class isn't loaded correctly, and slim are using it's CallableResolver class???

Thanks a lot,
BoGnY

**Comment by BoGnY** [comment]
Hi, I've solved my problem... I put "callableResolver" on wrong array depth, so is my fault :expressionless: :expressionless:

awesome plugin :+1: :+1: :+1:

**Comment by bnf** [comment]
Great it works for you!
