### ISSUE TITLE
Problems on using controllers for routes

### ISSUE THREAD

**Issue by BoGnY** [bnf/slim3-psr15#2]
Hi @bnf, I've found a problem if I try to use class on routes...

I've made for you a simple mcve project based on akrabat slim3 skeleton, which you found here: https://github.com/BoGnY/slim3-psr15-test

you can view on latest commit the few lines of code to implement your packages, and if I comment line [app/settings.php#L24](https://github.com/BoGnY/slim3-psr15-test/blob/b6d4b72e90b0d67291879177c59f44755b1ab9c2/app/settings.php#L24) the site work, otherwise i get this error:

> Slim Application Error
> The application could not run because of the following error:
> 
> 
> Details
> Type: TypeError
> Message: Argument 1 passed to App\Action\HomeAction::__construct() must be an instance of Slim\Container, null given, called in C:\wamp\www\yav-website\vendor\bnf\slim3-psr15\src\CallableResolver.php on line 76
> File: C:\wamp\www\yav-website\app\src\Action\HomeAction.php
> Line: 15
> Trace
> #0 C:\wamp\www\yav-website\vendor\bnf\slim3-psr15\src\CallableResolver.php(76): App\Action\HomeAction->__construct(NULL)
> #1 C:\wamp\www\yav-website\vendor\slim\slim\Slim\CallableResolverAwareTrait.php(45): Bnf\Slim3Psr15\CallableResolver->resolve('App\\Action\\Home...')
> #2 C:\wamp\www\yav-website\vendor\slim\slim\Slim\Route.php(330): Slim\Routable->resolveCallable('App\\Action\\Home...')
> #3 C:\wamp\www\yav-website\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
> #4 C:\wamp\www\yav-website\vendor\slim\slim\Slim\Route.php(313): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
> #5 C:\wamp\www\yav-website\vendor\slim\slim\Slim\App.php(495): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
> #6 C:\wamp\www\yav-website\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
> #7 C:\wamp\www\yav-website\vendor\slim\slim\Slim\App.php(388): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
> #8 C:\wamp\www\yav-website\vendor\slim\slim\Slim\App.php(296): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
> #9 C:\wamp\www\yav-website\public\index.php(27): Slim\App->run()
> #10 {main}

It's a my misconfiguration error??
Thanks a lot

**Comment by bnf** [comment]
Thanks for your example. That's indeed a bug in the example usage.
The container needs to be passed as first argument to the CallableResolver to work for that case.
I have adapted the example in README.md in f59a76b

**Comment by BoGnY** [comment]
thanks a lot 👍
